-- ADMIN TABLW
CREATE TABLE admin(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(30)
)DEFAULT CHARACTER SET UTF8 ENGINE=INNODB;

-- BOOK TABLE
CREATE TABLE book(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    author VARCHAR(30) NOT NULL,
    summery TEXT,
    date_of_pub DATE,
    pub_by VARCHAR(30) NOT NULL,
    copy_avl INT(6) NOT NULL,
    book_cover VARCHAR(30) NOT NULL,
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_name VARCHAR(30) NOT NULL,
    cat_id INT UNSIGNED,
    sub_id INT UNSIGNED
    FOREIGN KEY (user_name) REFERENCES admin(user_name)

)DEFAULT CHARACTER SET UTF8 ENGINE=INNODB;

-- Username and password
INSERT INTO admin(user_name,password) VALUES('deep','123456');

-- CATEGORY TABLE
CREATE TABLE categories(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL ,
    descrip VARCHAR(30),
    parent_id  INT(10) NOT NULL DEFAULT 0)
    DEFAULT CHARACTER SET UTF8 ENGINE=INNODB;

--  aLTER BOOK TABLE
-- ALTER TABLE book
-- ADD book_cat INT UNSIGNED NOT NULL,
-- ADD FOREIGN KEY (book_cat) REFERENCES categories(id)
-- ON DELETE NO ACTION ON UPDATE CASCADE;   